### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by gzzx2021** [free5gc/gtp5g#7]
Thanks for your help. I find a issue when i execute "make clean && make",the result is following:
:~/gtp5g$ make clean && make
make -C /usr/src/linux-headers-5.11.0-31-generic/ M=/home/gzzx/gtp5g  clean
make[1]: access folder “/usr/src/linux-headers-5.11.0-31-generic”
make[1]: exit folder“/usr/src/linux-headers-5.11.0-31-generic”
make -C /usr/src/linux-headers-5.11.0-31-generic/ M=/home/gzzx/gtp5g  modules
make[1]: access folder“/usr/src/linux-headers-5.11.0-31-generic”
  CC [M]  /home/gzzx/gtp5g/gtp5g.o
/home/gzzx/gtp5g/gtp5g.c:1499:27: error: ‘ip_tunnel_get_stats64’ undeclared here (not in a function); did you mean ‘ip_tunnel_get_ttl’?
 1499 |     .ndo_get_stats64    = ip_tunnel_get_stats64,
      |                           ^~~~~~~~~~~~~~~~~~~~~
      |                           ip_tunnel_get_ttl
make[2]: *** [scripts/Makefile.build:287：/home/gzzx/gtp5g/gtp5g.o] error 1
make[1]: *** [Makefile:1848：/home/gzzx/gtp5g] error 2
make[1]: exit folder“/usr/src/linux-headers-5.11.0-31-generic”
make: *** [Makefile:15：all] error 2

linux version: cat /proc/version
Linux version 5.11.0-31-generic (buildd@lcy01-amd64-009) (gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0, GNU ld (GNU Binutils for Ubuntu) 2.36.1) #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021

**Comment by gzzx2021** [comment]
Hi I reinstall linux system(Ubantu 20.04),the isssue make failure is also exist.Could you help me to solve this problem?

**Comment by free5gc-org** [comment]
@gzzx2021 

Please downgrade your linux kernel version to `5.4.x`.

**Comment by boeboe** [comment]
@gzzx2021 

You can patch the code to adopt the new name of this function (https://www.mail-archive.com/netdev@vger.kernel.org/msg366462.html).


    # uname -a
    Linux bastion 5.11.0-1021-aws #22~20.04.2-Ubuntu SMP Wed Oct 27 21:27:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

    # sed -i 's/ip_tunnel_get_stats64/dev_get_tstats64/g' gtp5g.c

    # make clean && make && sudo make install
    make -C /usr/src/linux-headers-5.11.0-1021-aws/ M=/tmp/gtp5g  clean
    make[1]: Entering directory '/usr/src/linux-headers-5.11.0-1021-aws'
    make[1]: Leaving directory '/usr/src/linux-headers-5.11.0-1021-aws'
    make -C /usr/src/linux-headers-5.11.0-1021-aws/ M=/tmp/gtp5g  modules
    make[1]: Entering directory '/usr/src/linux-headers-5.11.0-1021-aws'
    CC [M]  /tmp/gtp5g/gtp5g.o
    MODPOST /tmp/gtp5g/Module.symvers
    CC [M]  /tmp/gtp5g/gtp5g.mod.o
    LD [M]  /tmp/gtp5g/gtp5g.ko
    BTF [M] /tmp/gtp5g/gtp5g.ko
    Skipping BTF generation for /tmp/gtp5g/gtp5g.ko due to unavailability of vmlinux
    make[1]: Leaving directory '/usr/src/linux-headers-5.11.0-1021-aws'
    modprobe udp_tunnel
    cp gtp5g.ko /lib/modules/`uname -r`/kernel/drivers/net
    depmod -a
    modprobe gtp5g
    echo "gtp5g" >> /etc/modules

    # sudo init 6

    # lsmod | grep gtp
    gtp5g                 106496  0
    udp_tunnel             20480  1 gtp5g



@free5gc-org would you consider releasing a patch or a new version of this kernel module?

**Comment by raulkviana** [comment]
Hello, @boeboe. 
I tried to use your solution, but I got another error:

#sudo make clean && make && sudo make install

make -C /lib/modules/5.11.0-43-generic/build M=/home/babix/gtp5g  clean
make[1]: Entering directory '/usr/src/linux-headers-5.11.0-43-generic'
  CLEAN   /home/babix/gtp5g/Module.symvers
make[1]: Leaving directory '/usr/src/linux-headers-5.11.0-43-generic'
make -C /lib/modules/5.11.0-43-generic/build M=/home/babix/gtp5g  modules
make[1]: Entering directory '/usr/src/linux-headers-5.11.0-43-generic'
  CC [M]  /home/babix/gtp5g/gtp5g.o
  MODPOST /home/babix/gtp5g/Module.symvers
  CC [M]  /home/babix/gtp5g/gtp5g.mod.o
  LD [M]  /home/babix/gtp5g/gtp5g.ko
  BTF [M] /home/babix/gtp5g/gtp5g.ko
Skipping BTF generation for /home/babix/gtp5g/gtp5g.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/linux-headers-5.11.0-43-generic'
make -C /lib/modules/5.11.0-43-generic/build M=$PWD INSTALL_MOD_PATH= INSTALL_MOD_DIR=/kernel/drivers/net modules_install	
make[1]: Entering directory '/usr/src/linux-headers-5.11.0-43-generic'
  INSTALL /home/babix/gtp5g/gtp5g.ko
At main.c:160:
SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  5.11.0-43-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-5.11.0-43-generic'
modprobe udp_tunnel
true
modprobe gtp5g
modprobe: FATAL: Module gtp5g not found in directory /lib/modules/5.11.0-43-generic
make: *** [Makefile:46: install] Error 1


Could you help me out?

**Comment by raulkviana** [comment]
Instead of solving the issue above, I downgrade the kernel and then added to the linux-headers-5.4.x-91-generic the file System.map (from boot directory). And it worked.

**Comment by minziran** [comment]
Same problem.
~/gtp5g$ uname -r
5.4.0-84-generic

~/gtp5g$ sudo make install
make -C /lib/modules/5.4.0-84-generic/build M=$PWD INSTALL_MOD_PATH= INSTALL_MOD_DIR=/kernel/drivers/net modules_install	
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-84-generic'
  INSTALL /home/minziran/gtp5g/gtp5g.ko
At main.c:204:
- SSL error:0909006C:PEM routines:get_name:no start line: ../crypto/pem/pem_lib.c:745
sign-file: certs/signing_key.x509: Success
  DEPMOD  5.4.0-84-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-84-generic'
modprobe udp_tunnel
true
modprobe gtp5g
modprobe: FATAL: Module gtp5g not found in directory /lib/modules/5.4.0-84-generic
make: *** [Makefile:46: install] Error 1

**Comment by minziran** [comment]
Problem solved.
Run sudo depmod before sudo make install

**Comment by muthuramanecs03g** [comment]
@gzzx2021 

You can reopen the issue if your problem still exists.

**Comment by saileshvvr** [comment]
The issue still exists. Could you please help to resolve.

~/5gc/gtp5g$ sudo make install
cp gtp5g.ko /lib/modules//
modprobe udp_tunnel
/sbin/depmod -a
modprobe gtp5g
modprobe: FATAL: Module gtp5g not found in directory /lib/modules/5.13.0-27-generic
make: *** [Makefile:52: install] Error 1
~/5gc/gtp5g$ uname -r
5.13.0-27-generic
~/5gc/gtp5g$
